- name: Install NFS client package
  apt:
    name: nfs-common
    state: present
  become: yes

- name: Add NFS mount to fstab
  lineinfile:
    path: /etc/fstab
    line: "192.168.68.16:/volume1/downloads /mnt/downloads nfs rw,sync 0 0"
    state: present
    create: yes
  become: yes

- name: Create mount point
  file:
    path: /mnt/downloads
    state: directory
    mode: 0777
  become: yes

- name: Mount NFS share
  mount:
    path: /mnt/downloads
    src: "192.168.68.16:/volume1/downloads"
    fstype: nfs
    opts: "rw,sync"
    state: mounted
  become: yes

- name: install docker and docker-compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
  become: yes

- name: Add Docker user to sudo group
  user:
    name: docker
    groups: sudo
    append: yes

- name: Create folder for docker compose
  file:
    path: /home/simone/docker-compose
    state: directory
    owner: simone
    group: simone
    mode: 0755

- name: copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/simone/docker-compose/docker-compose.yml
    owner: simone
    group: simone
    mode: 0644

- name: Create Star Apps folder
  file:
    path: /home/simone/star-apps
    state: directory
    recurse: yes
    owner: simone
    group: simone
    mode: 0755

- name: Copy Starr App Config Files
  copy:
    src: files/star-apps/
    dest: /home/simone/star-apps/
    owner: simone
    group: simone
    mode: 0775
    remote_src: true

- name: Decrypt Star Config Files
  shell: ansible-vault decrypt --vault-password-file /home/chris/.vault_key "{{ item }}"
    #  no_log: True
  loop:
    - star-apps/radarr/radarr_config.xml
    - star-apps/sonarr/sonarr_config.xml
    - star-apps/sabnzbd/sabnzbd_config.ini

- name: Copy Star app configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: '/home/chris/ansible_tutorial/roles/downloader/files/star-apps/radarr/radarr_config.xml', dest: '/home/simone/star-apps/radarr/config.xml' }
    - { src: '/home/chris/ansible_tutorial/roles/downloader/files/star-apps/sonarr/sonarr_config.xml', dest: '/home/simone/star-apps/sonarr/config.xml' }
    - { src: '/home/chris/ansible_tutorial/roles/downloader/files/star-apps/sabnzbd/sabnzbd_config.ini', dest: '/home/simone/star-apps/sabnzbd/sabnzbd.ini' }

- name: Update permissions on Star app files
  file:
    path: "{{ item }}"
    owner: simone
    group: simone
    mode: 0644
  loop:
    - /home/simone/star-apps/radarr/config.xml
    - /home/simone/star-apps/sonarr/config.xml
    - /home/simone/star-apps/sabnzbd/sabnzbd.ini

- name: Start service
  command: docker-compose up -d
  args:
    chdir: /home/simone/docker-compose
