---
- hosts: localhost
  become: true
  vars:
    docker_user: chris
    nfs_mount_data:
      src: "192.168.68.132:/mnt/storage/data"
      dest: "/mnt/downloads/data"
    nfs_mount_configs:
      src: "192.168.68.132:/mnt/storage/Backups/docker-configs"
      dest: "/mnt/truenas/docker-configs"

  tasks:
    - name: Check if docker-group exists
      command: getent group docker-group
      register: docker_group
      ignore_errors: true

    - name: Include initial setup tasks if docker-group does not exist
      include_tasks: setup_users.yml
      when: docker_group.rc != 0

    - name: Always run these tasks
      include_tasks: main_tasks.yml
