---
version: "3.2"
services:
  radarr:
    container_name: radarr
    image: cr.hotio.dev/hotio/radarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/chris/star-apps/radarr:/config
      - /mnt/downloads/data:/data

  sonarr:
    container_name: sonarr
    image: cr.hotio.dev/hotio/sonarr:latest
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/chris/star-apps/sonarr:/config
      - /mnt/downloads/data:/data

  sonarr-4:
    container_name: sonarr-v4
    image: cr.hotio.dev/hotio/sonarr:nightly
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge
    ports:
      - 8990:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/chris/star-apps/sonarr-v4:/config
      - /mnt/downloads/data:/data
      
  sabnzb:
    container_name: sabnzbd
    image: cr.hotio.dev/hotio/sabnzbd
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - UMSAK=022
      - TZ=Europe/London
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/chris/star-apps/sabnzbd:/config
      - /mnt/downloads/data:/data

  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge
    ports:
      - 5454:5454
    volumes:
      - /home/chris/star-apps/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - UMAST=022
      - TZ=Europe/London
    volumes:
      - /mnt/downloads/data:/data
      - /home/chris/star-apps/emby:/config
    ports:
      - 8096:8096
    logging:
      driver: json-file
    networks:
      - docker_bridge
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Europe/London
    volumes:
      - /home/chris/star-apps/bazarr:/config
      - /mnt/downloads/data:/data
    ports:
      - 6767:6767
    restart: unless-stopped
    logging:
      driver: json-file
    networks:
      - docker_bridge

networks:
  docker_bridge:
    driver: bridge
